### ISSUE TITLE
Feature Request: ConvertImgToSrcSet for rte.cshtml

### ISSUE THREAD

**Issue by craigs100** [Jeavon/Slimsy#13]
Create a version of ConvertImgToSrcSet that can be applied safely to rte.cshtml so the Slimsy magic can work on all RTE's, even if in a grid layout. i.e.

@Html.ConvertImgToSrcSet(Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString())), true, true)

**Comment by Jeavon** [comment]
@craigs100 I think `@Html.ConvertImgToSrcSet(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))` will currently work, however I have made that method obsolete in v2.1.0-beta (likely to be released as v3 for Umbraco v8 now)....

**Comment by Jeavon** [comment]
In case any finds this, how to do it is shown in https://github.com/Jeavon/Slimsy/blob/dev-v3/TestSite/Views/Partials/Grid/Editors/Rte.cshtml#L10
