### ISSUE TITLE
Further options not supported

### ISSUE THREAD

**Issue by skttl** [Jeavon/Slimsy#14]
Just had a usecase, where I needed to use ImageProcessors Tint module. But Umbracos further options parameter is not supported in Slimsy.

**Comment by seanhak** [comment]
Same here actually. In my use case I need to position the image at the bottom togheter with boxpad. "&bgcolor=ffffff&anchor=bottom"

Edit: My "Quick & Dirty"-solution is String Replace.
`@imgSrcSetWebP.ToString().Replace("?","?bgcolor=ffffff&anchor=bottom&")`

**Comment by Jeavon** [comment]
This is now added in v3-beta5, sorry it took so long!
