### ISSUE TITLE
When add alt attribute the size change

### ISSUE THREAD

**Issue by pralthom** [Jeavon/Slimsy#19]
Hi,

I'm facing a strange issue.
When I add an alt attribute to the img tag, the image change size. Usually it small, but if I add more text in the "alt" tag, the image gets bigger.

My current workaround is to remove the attribute sizes="auto" but I guess this attribute shouldn't be removed?

Thank you in advance for the help,

Thomas

**Comment by steiniofur** [comment]
In the past I had [similar strange behavior](https://github.com/Jeavon/Slimsy/issues/4) when the alt tag was added. Then the solution was to make sure the image had the css rule display: block; for all images.  

What version of umbraco and slimsy are you using btw?

**Comment by craigs100** [comment]
I'm getting this issue too. With the following code which is used in a Carousel for both the main image and the thumbnails (but with a different crop for the thumbnails) the main image is poor quality and the thumbnails are odd sizes. If I take the alt attribute off, then all is correct.

`<img data-srcset="@Url.GetSrcSetUrls(image, "PropertyImage")"                                                 data-src="@Url.GetCropUrl(image, "PropertyImage")"  sizes="auto" class="lazyload" alt="@image.Name">`
