### ISSUE TITLE
An attempt was made to divide by zero

### ISSUE THREAD

**Issue by bjarnef** [Jeavon/Slimsy#2]
I am using Slimsy v1.1.7

I have an grid editor to insert some image boxes in the grid and futhermore option for the editors to set a height and width of the image, which will crop the image.

It also use LeBlender for this.

```
int width = 0;
int height = 0;

if (item.GetValue("width") != null)
{
    width = Convert.ToInt32(item.GetValue("width"));
}
if (item.GetValue("height") != null)
{
    height = Convert.ToInt32(item.GetValue("height"));
}

var url = image.GetResponsiveImageUrl(width, height);
```

however if width is zero it fails to generate the image: `An attempt was made to divide by zero.`
E.g. `var url = image.GetResponsiveImageUrl(0, 240);`

but not an issue height when height is zero.

In this case could it just ignore width or use the original width of the image?

This scale the image to `480px` in width
`/media/1234/my-image.jpg?anchor=center&mode=crop&width=480&heightratio=0.6&format=jpg&quality=90&slimmage=true&rnd=131027199800000000`

and with height to `100px` it crop is height to 100px.

`/media/1234/my-image.jpg?anchor=center&mode=crop&width=480&height=100&heightratio=0.6&format=jpg&quality=90&slimmage=true&rnd=131027199800000000`

**Comment by Jeavon** [comment]
I'm pretty sure this was fixed in Umbraco some time ago now....
