### ISSUE TITLE
WebP plug-in NOT installed with NuGet Package v3.0.0-beta-3

### ISSUE THREAD

**Issue by DanielOor365** [Jeavon/Slimsy#23]
When following the instructions, and installing Slimsy using
`Install-Package Our.Umbraco.Slimsy -Version 3.0.0-beta3`
the WebP plugin is NOT installed. 

This is also not really clearly stated in the docs:

> "Below is an example of how to use the <picture> element to provide automated WebP versions of your images using the ImageProcessor WebP plugin, this example also implements an optional LQIP image."

I would suggest to state in the docs that the ImageProcessor.Plugins.WebP needs to be installed for Umbraco to deliver WebP, or better, include the plugin as a dependency of Slimsy.

**Comment by Jeavon** [comment]
Thanks! I've added a note to say that the plugin must be installed from NuGet.
