### ISSUE TITLE
How do I uninstall Slimsy from Umbraco?

### ISSUE THREAD

**Issue by DonZalmrol** [Jeavon/Slimsy#3]
Hi Jeavon,

When I uninstall slimsy from the Umbraco Backend I receive numerous errors and the site won't load.
It's stating that the assembly still has references to Slimsy (and slimmage).

e.g. line 34: @using Slimsy;

How can I safely remove it from my Umbraco site?

Thank you & sincerely,

Laurens

**Comment by Jeavon** [comment]
You need to remove the namespace from /Views/Web.config
