### ISSUE TITLE
Error during installation process on Umbraco 7.4.3

### ISSUE THREAD

**Issue by Auraya86** [Jeavon/Slimsy#30]
Hi,

please see below the error message after installing the package Slimsy. It breaks during the installation process

```
Server Error in '/' Application.
Could not load all types from "Slimsy, Version=3.0.0.230, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Core.Composing.IUserComposer: Could not load type 'Umbraco.Core.Composing.IUserComposer' from assembly 'Umbraco.Core, Version=1.0.6073.15895, Culture=neutral, PublicKeyToken=null'.
. System.TypeLoadException on Umbraco.Core.PackageActions.IPackageAction: Could not load type 'Umbraco.Core.PackageActions.IPackageAction' from assembly 'Umbraco.Core, Version=1.0.6073.15895, Culture=neutral, PublicKeyToken=null'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Reflection.ReflectionTypeLoadException: Could not load all types from "Slimsy, Version=3.0.0.230, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Core.Composing.IUserComposer: Could not load type 'Umbraco.Core.Composing.IUserComposer' from assembly 'Umbraco.Core, Version=1.0.6073.15895, Culture=neutral, PublicKeyToken=null'.
. System.TypeLoadException on Umbraco.Core.PackageActions.IPackageAction: Could not load type 'Umbraco.Core.PackageActions.IPackageAction' from assembly 'Umbraco.Core, Version=1.0.6073.15895, Culture=neutral, PublicKeyToken=null'.
```

**Comment by Auraya86** [comment]
Hi,

I need help with installing this package. I got following error message 
`Server Error in '/' Application.
Could not load all types from "Slimsy, Version=3.0.0.230, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Core.Composing.IUserComposer: Could not load type 'Umbraco.Core.Composing.IUserComposer' from assembly 'Umbraco.Core, Version=1.0.6073.15895, Culture=neutral, PublicKeyToken=null'.
. System.TypeLoadException on Umbraco.Core.PackageActions.IPackageAction: Could not load type 'Umbraco.Core.PackageActions.IPackageAction' from assembly 'Umbraco.Core, Version=1.0.6073.15895, Culture=neutral, PublicKeyToken=null'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Reflection.ReflectionTypeLoadException: Could not load all types from "Slimsy, Version=3.0.0.230, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Core.Composing.IUserComposer: Could not load type 'Umbraco.Core.Composing.IUserComposer' from assembly 'Umbraco.Core, Version=1.0.6073.15895, Culture=neutral, PublicKeyToken=null'.
. System.TypeLoadException on Umbraco.Core.PackageActions.IPackageAction: Could not load type 'Umbraco.Core.PackageActions.IPackageAction' from assembly 'Umbraco.Core, Version=1.0.6073.15895, Culture=neutral, PublicKeyToken=null'.`

**Comment by Jeavon** [comment]
Hi @Auraya86 for Umbraco v7 you need to use Slimsy v2 not v3 as that's for Umbraco v8 only
