### ISSUE TITLE
Image show blur after apply slimsy

### ISSUE THREAD

**Issue by rbalai429** [Jeavon/Slimsy#32]
Hello, 
I am using slimsy in umbraco v8.4 and slimsy v3.0.0-beta1 but after apply once image show blur but when I do inspect element then remove blur effect from image. Can you please explain what the issue.

**Comment by Jeavon** [comment]
@RakeshKumar04 sounds like you are missing a sizing of the img via css, there is info here about it https://github.com/aFarkas/lazysizes#more-about-the-api
