### ISSUE TITLE
Slimsy needed for Umbraco 9?

### ISSUE THREAD

**Issue by dhymik** [Jeavon/Slimsy#39]
Hi Jeavon,

is Slimsy still useful for Umbraco 9, or are there new techniques in place to make it obsolete? WIll there be a Slimsy version for Umbraco 9?

Kind regards! Mikael

**Comment by Jeavon** [comment]
Hi @dhymik 

Yes work has begun on this branch https://github.com/Jeavon/Slimsy/tree/dev-v4 

However, we're are currently minded to wait for the ImageSharp v2 release which brings webp support before releasing Slimsy v4 (there will be pre-releases).

Thanks for your interest!

**Comment by dhymik** [comment]
Hi Jeavon,

thank you for your comment. Now that ImageSharp v2 is released, I would like to come back to it. Is there a v4 beta I could play with? I have several projects which are waiting for it 😅

Thank you for Slimsy 🙏🏻🙏🏻

**Comment by dhymik** [comment]
Hi Jeavon,

quick question, do you think[ https://github.com/Jeavon/Slimsy/tree/dev-v4]( https://github.com/Jeavon/Slimsy/tree/dev-v4) can be used on a development and demo site already? What's your take?

**Comment by Jeavon** [comment]
Hey @dhymik we are using it on production sites. Bear in mind that there's no webp support (unless you use a custom Umbraco build for ImageSharp2)

It's available from MyGet also https://www.myget.org/feed/umbraco-packages/package/nuget/Our.Umbraco.Slimsy

**Comment by dhymik** [comment]
Hey @Jeavon, thank you for getting back. This is good news, I will give it a try!

I am unclear about your remark about the lack of WebP support. Where is it lacking - in ImageSharp2? ImageSharp V2 supports WebP as of [this issue comment](https://github.com/SixLabors/ImageSharp/issues/121#issuecomment-1063225595).

**Comment by Jeavon** [comment]
Yes, ImageSharp v2 supports WebP and is released however ImageSharp.Web v2 is not yet released and contains breaking changes so at the earliest will be officially supported in Umbraco v10.0. 

We are running a custom version of Umbraco.Cms.Web.Common that is depending on the ImageSharp.Web v2 pre-release. It's in this branch of Slimsy https://github.com/Jeavon/Slimsy/tree/feature/ImageSharp2

**Comment by dvdvliet** [comment]
Hi @Jeavon, I was wondering now v10 has been released when you plan to release the v4 version. 

Thank you for a great package!

**Comment by Jeavon** [comment]
@dvdvliet we are very close, we've just been adding a tag helper which should make things even easier - https://github.com/Jeavon/Slimsy/blob/dev-v4/src/Slimsy.TestSite/Views/people.cshtml#L44

**Comment by Jeavon** [comment]
Slimsy v4-beta1 is out on NuGet! Please do try and let us know how it goes!
