### ISSUE TITLE
Strange size when alt and title* attributes are more than 5 characters 

### ISSUE THREAD

**Issue by steiniofur** [Jeavon/Slimsy#4]
When testing the new beta version I ran across a strange issue. 

I am using Url.GetSrcSetUrls(publishedContent, cropAlias, propertyAlias) method - it works as it should - freaking awesome!

Then I decide to add an alt attribute to please the seo gods, and after that the image loads but in the smallest size. Strange.

If the alt attribute is empty - everything is fine, and up to 5 characters it seems, but after 6 the smallest version is loaded.

Before adding the alt, the size was set to sizes="1663px", but after adding the alt it is sizes="46px"*
*it gets longer in relation to how long the alt attribute is set, 6 characters gives me 46px .

The same happens if I add a title attribute, if I have it longer than 5 characters, the smallest version of the image is loaded. BUT if I also add an alt attribute, and it is empty or not longer than 5 characters, I can have the title tag as long as I wish.

Am I doing something wrong here?

**Comment by Jeavon** [comment]
Thanks for trying out the beta and the feedback!

It is a strange one but we were able to replicate and find a solution! You need to ensure that your image elements have display:block on them.

To test inline add style="display: block;" to your img elements

**Comment by Jeavon** [comment]
I have amended the readme to include this info!

**Comment by steiniofur** [comment]
Great - this seems to solve this for me too.
Thank you!
