### ISSUE TITLE
When using webp, the quality parameter must be the last

### ISSUE THREAD

**Issue by kritollm** [Jeavon/Slimsy#46]
<img width="1616" alt="image" src="https://user-images.githubusercontent.com/12444201/201039653-1285c759-d23b-41f9-9111-2680734e0428.png">

**Comment by kritollm** [comment]
The problem is in ImageSharp, so I close it.

**Comment by Jeavon** [comment]
@kritollm Could you explain a bit more, we could possibly re-arrange the order as a temporary fix, we did something simular in a old version

**Comment by kritollm** [comment]
@Jeavon Hi. I'm hunting the bug now. Format should always run before quality because of this check in the Quality Processor. ImageSharp.Web

<img width="536" alt="image" src="https://user-images.githubusercontent.com/12444201/201065446-bf15f994-bb97-46a3-9702-220759c395e0.png">

**Comment by Jeavon** [comment]
@kritollm Cool, let me know how it goes

**Comment by kritollm** [comment]
@Jeavon https://github.com/umbraco/Umbraco-CMS/issues/13378

**Comment by Jeavon** [comment]
Cheers! I actually remember this same issue being fixed long ago for v7 and ImageProcessor! https://github.com/umbraco/Umbraco-CMS/pull/1398
