### ISSUE TITLE
Add the possibility of changing webp quality

### ISSUE THREAD

**Issue by julieteg** [Jeavon/Slimsy#53]
Please, add the possibility of changing the webp quality in the SlimsyPictureTagHelper.

Today it's fixed on 70% in the code and we wanted to use a custom value there.

**Comment by Jeavon** [comment]
@julieteg Yes, we will do that. In v4.1 we've made a bit more configurable to support multiple formats, in the example below might you want to set the quality to be different for webp and avif or should it be a single setting do you think?

```
  "Slimsy": {
    "WidthStep": 180,
    "UseCropAsSrc": false,
    "DefaultQuality": 70,
    "Format": "",
    "BGColor": "",
    "TagHelper": {
      "SingleSources": [ "gif" ],
      "PictureSources": [ "webp", "avif" ]
    }
  }
```

**Comment by julieteg** [comment]
I think you can give us the option of setting the quality of Webp and Avif separately :)

**Comment by Jeavon** [comment]
@julieteg Yes, for defaults, we put this together

```
  "Slimsy": {
    "WidthStep": 180,
    "UseCropAsSrc": false,
    "DefaultQuality": 70,
    "Format": "",
    "BGColor": "",
    "TagHelper": {
      "SingleSources": [ "gif" ],
      "DefaultPictureSources": [
        {
          "Extension": "webp",
          "Quality": "90"
        },
        {
          "Extension": "avif",
          "Quality":  "100"
        }
      ]
    }
  }
```
But I also think that you might have a specific usage where you want to boost the quality so I'm going to look at adding a parameter to the tag helper also
