### ISSUE TITLE
SVG support needed

### ISSUE THREAD

**Issue by sekmenhuseyin** [Jeavon/Slimsy#59]
I am using slimsy with these settings

`.AddSlimsy()`

```
<slimsy-picture 
    media-item="@item.Image"
    alt-text="@item.Image!.GetAltText()"
    width="64"
    height="64"
    css-class="logo"
></slimsy-picture>
```

but svg files do not show. they have "jpg" as format settings

![image](https://github.com/Jeavon/Slimsy/assets/1363876/9fa74da0-dac0-4dec-bc8a-7ec2efc981c7)

what do I need to show SVG files correctly

**Comment by Jeavon** [comment]
@sekmenhuseyin Could you try with 4.1.0-beta4 and see if it does something different?

**Comment by sekmenhuseyin** [comment]
@Jeavon yes, beta version is working great
