### ISSUE TITLE
Documentation on DefaultPictureSources?

### ISSUE THREAD

**Issue by robertjf** [Jeavon/Slimsy#62]
Hey @Jeavon, can you provide some guidance/documentation on the following issue (since upgradng)?

![image](https://github.com/Jeavon/Slimsy/assets/818101/47e2246b-1699-4fdd-97cb-4e3d42c56696)

I can't work out what is needed in the appSettings configuration to configure this...

**Comment by Jeavon** [comment]
Hey @robertjf 

For only webp, something like this:

```
 "Slimsy": {
    "WidthStep": 180,
    "UseCropAsSrc": true,
    "DefaultQuality": 70,
    "TagHelper": {
      "SingleSources": [ "gif" ],
      "DefaultPictureSources": [
        {
          "Extension": "webp",
          "Quality": 70
        }
      ],
      "ImageDimensions": true
    }
  }
```

**Comment by Jeavon** [comment]
More info is here https://github.com/Jeavon/Slimsy#available-in-v41

**Comment by robertjf** [comment]
@Jeavon so if I configure DefaultPictureSources like that, will it convert a png to webp?  As that was myunderstanding of the original `render-webp-alternative` attribute - it's not clear what exactly DefaultPictureSources actually does...

**Comment by Jeavon** [comment]
@robertjf yes it will provide a webp source element for all origin image types. It should be exactly the same as render-webp-alternative

**Comment by robertjf** [comment]
perfect - thanks @Jeavon :)
