### ISSUE TITLE
Not converting WEBP on Umbraco 12

### ISSUE THREAD

**Issue by ShadeRF** [Jeavon/Slimsy#64]
Using the following in Umbraco 12 and query string for format= is matching the source file and not setting format=webp for conversion.

<slimsy-picture media-item="@post.Photo" width="398" height="266" css-class="lazyload" render-lqip="true" render-webp-alternative="true"></slimsy-picture>

Appsettings as follows:

  "Slimsy": {
    "WidthStep": 180,
    "UseCropAsSrc": true,
    "DefaultQuality": 70,
    "TagHelper": {
      "SingleSources": [ "gif" ],
      "DefaultPictureSources": [
        {
          "Extension": "webp",
          "Quality": 70
        }
      ],
      "ImageDimensions": true
    }
  }
<img width="331" alt="Screenshot 2023-09-20 192527" src="https://github.com/Jeavon/Slimsy/assets/20115489/a5fe1885-4107-4144-b727-d4dbfd70b8f5">

**Comment by Jeavon** [comment]
What do you see if you view the source rather than inspecting the DOM? You should find multiple `source `elements within the `picture` element

**Comment by ShadeRF** [comment]
Thanks for the reply, viewing source I do see the other sourceset, however, it does not appear to be utilized when looking at what is actually transferring in the network tab. Please advise.

**Comment by Jeavon** [comment]
You should see something like this:
![image](https://github.com/Jeavon/Slimsy/assets/1829920/fb05604f-ccba-4b15-823e-6dc872e1be44)
Ensure you are [loading lazysizes.js](https://github.com/Jeavon/Slimsy#4-add-lazysizesminjs--to-your-templatesviews) and also that your CSS is applying to images as documented [here](https://github.com/Jeavon/Slimsy#4-add-lazysizesminjs--to-your-templatesviews)

**Comment by ShadeRF** [comment]
I do have my configuration as outlined in the setup doc. What I have discovered with some additional testing is that removing the files being served from CDN gives me a result similar to that outlined in your screenshot. When they are served from the CDN they come across as jpeg type even though they show format=webp. I do have my CDN set to cache every unique URL so I'm not sure what's going on there.

**Comment by Jeavon** [comment]
Ah sounds like the CDN may have cached ignoring querystrings, or is still ignoring querystrings perhaps

**Comment by ShadeRF** [comment]
I have it configured as shown here, along with a custom domain - https://github.com/Jeavon/Slimsy/blob/dev-v3/Docs/Azure-CDN/index.md

Is there anything else I should be looking for?

**Comment by Jeavon** [comment]
And set to "Cache every unique URL"? Maybe try a purge to see if it cached previously

**Comment by ShadeRF** [comment]
After setting up a new cdn with azure front door I was able to get functionality nearly as expected. However, once caching is enabled all the images served are very low quality versions only even though the request looks correct in the network tab.

<img width="741" alt="image" src="https://github.com/Jeavon/Slimsy/assets/20115489/3dc2dbd0-8fd0-4156-afaa-546f72b9e0cd">

**Comment by ShadeRF** [comment]
A bit more digging and I'm almost there. All the CDN stuff and serving is good. The only hangup I have left is with the conversion of content in RTE. 

Not all images are being updated to the srcset format. For instance, if I insert an image with the media picker you get the following code, which does not convert when rendered...

<img width="751" alt="image" src="https://github.com/Jeavon/Slimsy/assets/20115489/72df5907-7c0a-4796-b77e-296445f1e4f3">

<img width="250" alt="image" src="https://github.com/Jeavon/Slimsy/assets/20115489/de86eaef-f017-44c9-9eb1-29c0a073290a">


However if you add a query string with the width and height manually it will convert.

<img width="684" alt="image" src="https://github.com/Jeavon/Slimsy/assets/20115489/2882c894-cb85-49fa-a0c2-fce7a176e7fc">


<img width="422" alt="image" src="https://github.com/Jeavon/Slimsy/assets/20115489/2f441f7f-7b35-496b-b8d5-3bb29ba13a2f">


Is the height and width query string required or should it be detecting all <img> tags regardless?

**Comment by damian-clarke-wearemci** [comment]
Seem to be having the same @ShadeRF, are we missing something - do you have to add the width and/or height in the querystring of the image src?

**Comment by Jeavon** [comment]
@damian-clarke-wearemci ahh, so images without any resizing aren't getting converted?

**Comment by Jeavon** [comment]
I'm wondering how you insert a image into the RTE that doesn't have a size, I've tried and it's always adding one....

**Comment by Jeavon** [comment]
I have pushed up a fix for this and it seems to be working well in my testing so far. If you can test it's available as pre-release

` dotnet add package Our.Umbraco.Slimsy --version 5.1.2-alpha.539 --source https://www.myget.org/F/umbraco-packages/api/v3/index.json`

**Comment by damian-clarke-wearemci** [comment]
Thanks for looking into it. I applied the pre-release. In my example I have a 900x700 image in a two column row and it works if you omit height and width from the src url, providing you add width and height properties to the img tag, which would be good practice.

If you omit height and width from the src url and the img tag, you get an image which is 180x140 for all screen widths, which is not so good.

I think you are correct to say that in most cases the RTE adds a height and width property, it is only if the user edits the source html that they might get no effect or unexpected results.

**Comment by Jeavon** [comment]
@damian-clarke-wearemci cool, I've been thinking about handling various combos of querystrings and attributes, I'm going to refactor the way it's working atm to favour using attributes, then querystrings instead. I'll let you know when there's a new pre-release

**Comment by Jeavon** [comment]
@damian-clarke-wearemci ok I have refactored and it's looking good from my testing, it's available on myget if you want to give it a try 
`dotnet add package Our.Umbraco.Slimsy --version 5.1.2-alpha.542 --source https://www.myget.org/F/umbraco-packages/api/v3/index.json`

**Comment by Jeavon** [comment]
Fixed in v5.1.2 & v6.0.0-beta2
