### ISSUE TITLE
Need help in media queries

### ISSUE THREAD

**Issue by sekmenhuseyin** [Jeavon/Slimsy#65]
Hi,
We are trying to get an HTML response as below with your plugin but we couldn't create the custom breakpoints. we do not want auto generated breakpoints. is it possible to do it with this package

![image](https://github.com/Jeavon/Slimsy/assets/1363876/67d66537-3efc-4a4b-8193-119487d29cac)

```
<picture>
    <source media="(min-width: 1440px)" srcset="/media/tytmj3of/web-header-darkb.jpg?rxy=0.7057628900729893%2c0.23142480436991725&amp;width=1920&amp;height=584&amp;rnd=133330203507330000&amp;format=webp&amp;quality=80 1x, /media/tytmj3of/web-header-darkb.jpg?rxy=0.7057628900729893%2c0.23142480436991725&amp;width=3840&amp;height=1168&amp;rnd=133330203507330000&amp;format=webp&amp;quality=80 2x" type="image/webp">
    <source media="(min-width: 768px)" srcset="/media/tytmj3of/web-header-darkb.jpg?rxy=0.7057628900729893%2c0.23142480436991725&amp;width=1200&amp;height=464&amp;rnd=133330203507330000&amp;format=webp&amp;quality=80 1x, /media/tytmj3of/web-header-darkb.jpg?rxy=0.7057628900729893%2c0.23142480436991725&amp;width=2400&amp;height=928&amp;rnd=133330203507330000&amp;format=webp&amp;quality=80 2x" type="image/webp">
    <source media="(min-width: 375px)" srcset="/media/tytmj3of/web-header-darkb.jpg?cc=0.48653172261789%2c0%2c0.07131845920029152%2c0&amp;width=768&amp;height=528&amp;rnd=133330203507330000&amp;format=webp&amp;quality=80 1x, /media/tytmj3of/web-header-darkb.jpg?cc=0.48653172261789%2c0%2c0.07131845920029152%2c0&amp;width=1536&amp;height=1056&amp;rnd=133330203507330000&amp;format=webp&amp;quality=80 2x" type="image/webp">
    <img class="event-page__imag header-block__image" srcset="/media/tytmj3of/web-header-darkb.jpg?rxy=0.7057628900729893%2c0.23142480436991725&amp;width=1920&amp;height=584&amp;rnd=133330203507330000&amp;format=webp&amp;quality=80 1x, /media/tytmj3of/web-header-darkb.jpg?rxy=0.7057628900729893%2c0.23142480436991725&amp;width=3840&amp;height=1168&amp;rnd=133330203507330000&amp;format=webp&amp;quality=80 2x" alt="Web Header Darkb" loading="eager" height="584" width="1920">
</picture>
```

**Comment by ShadeRF** [comment]
A bit more digging and I'm almost there. All the CDN stuff and serving is good. The only hangup I have left is with the conversion of content in RTE. 

Not all images are being updated to the srcset format. For instance, if I insert an image with the media picker you get the following code, which does not convert when rendered...

<p><img src="/media/u0ufjnrb/copy-of-calories-per-gram-of-each-macro.png" alt="" data-udi="umb://media/b654a8a06d214a4f99d5f4a1004af327"></p>

<img width="250" alt="image" src="https://github.com/Jeavon/Slimsy/assets/20115489/de86eaef-f017-44c9-9eb1-29c0a073290a">


However if you add a query string with the width and height manually it will convert.

<img src="/media/u0ufjnrb/copy-of-calories-per-gram-of-each-macro.png?width=374&amp;height=56" alt="" data-udi="umb://media/b654a8a06d214a4f99d5f4a1004af327">

<img width="422" alt="image" src="https://github.com/Jeavon/Slimsy/assets/20115489/2f441f7f-7b35-496b-b8d5-3bb29ba13a2f">


Is the height and width query string required or should it be detecting all <img> tags regardless?

**Comment by Jeavon** [comment]
No, this package is made so so that everything is automatic
