### ISSUE TITLE
Umbraco v13 ConvertImgToResponsive methods are broken

### ISSUE THREAD

**Issue by Jeavon** [Jeavon/Slimsy#74]
Umbraco v13 have changed the objects returned by the RteMacroRenderingValueConverter which breaks how Slimsy works

There is a pending PR to make this possible to fix in a future v13 targeted release https://github.com/umbraco/Umbraco-CMS/pull/15645

**Comment by mikecp** [comment]
The PR has been merged and should be included in V13.2.0.

**Comment by Jeavon** [comment]
Thanks Mike!

**Comment by Jeavon** [comment]
For anyone who can't wait for Umbraco v13.2 we have "hacked" version of Slimsy for Umbraco v13.1.1 on MyGet - https://www.myget.org/feed/umbraco-packages/package/nuget/Our.Umbraco.Slimsy/5.0.0-alpha.487
We will make a proper Slimsy v5 release once Umbraco v13.2 is released.

**Comment by Jeavon** [comment]
Fixed in v5.0.0
