### ISSUE TITLE
Where to put .AddSlimsy() in Umb13?

### ISSUE THREAD

**Issue by Eaglef90** [Jeavon/Slimsy#77]
Umbraco 13 does not have a startup.cs file and I can't figure out where to put the ".AddSlimsy()" command. I saw a post here on Umbraco 11's location but "services.AddUmbraco()" does not seem to exist in an Umbraco 13 project either so I am a bit lost on this. What is the proper config for an Umbraco 13 install? Thank you

**Comment by Jeavon** [comment]
Add it in program.cs, just like this https://github.com/Jeavon/Slimsy/blob/dev-v6/src/Slimsy.TestSite/Program.cs#L10

**Comment by Eaglef90** [comment]
Thanks. Last night at work it dawned on me I might be able to dig though a test site if you had one for Umb 13 and was going to look this morning when I got home but you beet me to it. Sorry about that.

**Comment by Jeavon** [comment]
It's all good, I have updated the readme in the default branch too. I need to clean it up a bit more for v13/v14 rather than all versions
