### ISSUE TITLE
Using a Crop (unable to set width for LowQ image)

### ISSUE THREAD

**Issue by uniquelau** [Jeavon/Slimsy#9]
Firstly thank-you for v2, much kudos!

I've had a spin, and it's working really nicely, however once I set a CropAlias on the GetCropUrl method, I seem unable to set the width/height and quality. I figured, I would need to do this to make the Low Quality image fallback work?

Loads of detail below on how I'm using it, however I won't be offended if TLDR ;-)

## Implementation

I've implemented in a project via a single DisplayTemplate.

`@Html.DisplayFor(m => Model.Photo)`

I also support passing in some parameters:

`@Html.DisplayFor(m => Model.Photo, new { Crop = "carousel", Width = 100, Height = 100 })`

## Example of issue

Works: `var imgLqip = Url.GetCropUrl(Model.Content, width, height, quality: 30, furtherOptions: "&format=auto");`

Works: `var imgLqip = Url.GetCropUrl(Model.Content, cropAlias);`

Fails: `var imgLqip = Url.GetCropUrl(Model.Content, cropAlias, width);`

## Full Display Template

```razor
@model Image
@if (Model != null)
{
    var cropAlias = (string)ViewData["crop"];
    int width = (int?)ViewData["width"] ?? 640;
    int height = (int?)ViewData["height"] ?? 0;

    // load javascript
    Html.RequiresJs("~/scripts/vendor/picturefill.min.js");
    Html.RequiresJs("~/scripts/vendor/lazysizes.min.js");

    if (cropAlias == null)
    {
        var imgSrcSet = Url.GetSrcSetUrls(Model.Content, width, height);
        var imgSrcSetWebP = Url.GetSrcSetUrls(Model.Content, width, height, Constants.Conventions.Media.File, "webp", 70);

        var imgSrc = Url.GetCropUrl(Model.Content, width, height);
        var imgLqip = Url.GetCropUrl(Model.Content, width, height, quality: 30, furtherOptions: "&format=auto");

        <picture>
            <!--[if IE 9]><video style="display: none"><![endif]-->
            <source data-srcset="@imgSrcSetWebP" srcset="@imgLqip" type="image/webp" data-sizes="auto" />
            <source data-srcset="@imgSrcSet" srcset="@imgLqip" type="image/jpeg" data-sizes="auto" />
            <!--[if IE 9]></video><![endif]-->
            <img src="@imgLqip"
                 data-src="@imgSrc"
                 class="lazyload"
                 data-sizes="auto"
                 alt="@Model.Name" />
        </picture>
    }
    else
    {
        var imgSrcSet = Url.GetSrcSetUrls(Model.Content, cropAlias);
        var imgSrcSetWebP = Url.GetSrcSetUrls(Model.Content, cropAlias, Constants.Conventions.Media.File, "webp");

        var imgSrc = Url.GetCropUrl(Model.Content, cropAlias);
        var imgLqip = Url.GetCropUrl(Model.Content, cropAlias);

        <picture>
            <!--[if IE 9]><video style="display: none"><![endif]-->
            <source data-srcset="@imgSrcSetWebP" srcset="@imgLqip" type="image/webp" data-sizes="auto" />
            <source data-srcset="@imgSrcSet" srcset="@imgLqip" type="image/jpeg" data-sizes="auto" />
            <!--[if IE 9]></video><![endif]-->
            <img src="@imgLqip"
                 data-src="@imgSrc"
                 class="lazyload"
                 data-sizes="auto"
                 alt="@Model.Name" />
        </picture>
    }
}

```

**Comment by uniquelau** [comment]
I think I've solved my own question:

        var imgLqip = Url.GetCropUrl(Model.Content, lowQualityWidth, height, quality: 50, furtherOptions: "&format=auto");

**Comment by Jeavon** [comment]
Hey @uniquelau great to hear you are liking v2 and that you've solved your own issue :)

Did you have a look at the sample helper? https://github.com/Jeavon/Slimsy/blob/develop/TestSite/App_Code/SlimsyHelper.cshtml
